eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
  instance:
    hostname: localhost
    
microservice:
  Payment_Microservices:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/payment/doPayment
  Order_Microservices:
    endpoints:
      endpoint:
        uri: http://UNKNOWN/order/bookorders 
